/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SymbolNodeHealthIcon {
        /**
          * The node url (REST gateway)
         */
        "nodeUrl": string;
    }
}
declare global {
    interface HTMLSymbolNodeHealthIconElement extends Components.SymbolNodeHealthIcon, HTMLStencilElement {
    }
    var HTMLSymbolNodeHealthIconElement: {
        prototype: HTMLSymbolNodeHealthIconElement;
        new (): HTMLSymbolNodeHealthIconElement;
    };
    interface HTMLElementTagNameMap {
        "symbol-node-health-icon": HTMLSymbolNodeHealthIconElement;
    }
}
declare namespace LocalJSX {
    interface SymbolNodeHealthIcon {
        /**
          * The node url (REST gateway)
         */
        "nodeUrl"?: string;
        /**
          * Emits the node health
         */
        "onFetched"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "symbol-node-health-icon": SymbolNodeHealthIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "symbol-node-health-icon": LocalJSX.SymbolNodeHealthIcon & JSXBase.HTMLAttributes<HTMLSymbolNodeHealthIconElement>;
        }
    }
}
