/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NetworkType, } from "symbol-sdk/dist/src/model/network/NetworkType";
export namespace Components {
    interface NodeHealthIcon {
        /**
          * The network generation hash
         */
        "generationHash"?: string;
        /**
          * The network type
         */
        "networkType"?: NetworkType;
        /**
          * The node url (REST gateway)
         */
        "nodeUrl"?: string;
    }
}
declare global {
    interface HTMLNodeHealthIconElement extends Components.NodeHealthIcon, HTMLStencilElement {
    }
    var HTMLNodeHealthIconElement: {
        prototype: HTMLNodeHealthIconElement;
        new (): HTMLNodeHealthIconElement;
    };
    interface HTMLElementTagNameMap {
        "node-health-icon": HTMLNodeHealthIconElement;
    }
}
declare namespace LocalJSX {
    interface NodeHealthIcon {
        /**
          * The network generation hash
         */
        "generationHash"?: string;
        /**
          * The network type
         */
        "networkType"?: NetworkType;
        /**
          * The node url (REST gateway)
         */
        "nodeUrl"?: string;
    }
    interface IntrinsicElements {
        "node-health-icon": NodeHealthIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "node-health-icon": LocalJSX.NodeHealthIcon & JSXBase.HTMLAttributes<HTMLNodeHealthIconElement>;
        }
    }
}
