/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NodeHealthStatus, } from "./models/NodeHealthStatus";
export namespace Components {
    interface SymbolNodeHealthIcon {
        /**
          * The node url (REST gateway)
         */
        "nodeUrl": string;
    }
    interface SymbolTransactionIcon {
        /**
          * The transaction type
         */
        "type": string;
    }
}
declare global {
    interface HTMLSymbolNodeHealthIconElement extends Components.SymbolNodeHealthIcon, HTMLStencilElement {
    }
    var HTMLSymbolNodeHealthIconElement: {
        prototype: HTMLSymbolNodeHealthIconElement;
        new (): HTMLSymbolNodeHealthIconElement;
    };
    interface HTMLSymbolTransactionIconElement extends Components.SymbolTransactionIcon, HTMLStencilElement {
    }
    var HTMLSymbolTransactionIconElement: {
        prototype: HTMLSymbolTransactionIconElement;
        new (): HTMLSymbolTransactionIconElement;
    };
    interface HTMLElementTagNameMap {
        "symbol-node-health-icon": HTMLSymbolNodeHealthIconElement;
        "symbol-transaction-icon": HTMLSymbolTransactionIconElement;
    }
}
declare namespace LocalJSX {
    interface SymbolNodeHealthIcon {
        /**
          * The node url (REST gateway)
         */
        "nodeUrl"?: string;
        /**
          * Emits the node health
         */
        "onFetched"?: (event: CustomEvent<NodeHealthStatus>) => void;
    }
    interface SymbolTransactionIcon {
        /**
          * The transaction type
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "symbol-node-health-icon": SymbolNodeHealthIcon;
        "symbol-transaction-icon": SymbolTransactionIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "symbol-node-health-icon": LocalJSX.SymbolNodeHealthIcon & JSXBase.HTMLAttributes<HTMLSymbolNodeHealthIconElement>;
            "symbol-transaction-icon": LocalJSX.SymbolTransactionIcon & JSXBase.HTMLAttributes<HTMLSymbolTransactionIconElement>;
        }
    }
}
